name: anime-dub-diar
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=12.1  # CUDA 12.1 build compatible with RTX 4080
  - ffmpeg=6.*
  - pip
  - numpy
  - openssl
  - pip:
      - pyannote.audio==3.1.1
      - torchcodec==0.2.0
      - soundfile
      - librosa
